name: Generate 3D Contributions

on:
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: contribution-3d-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Vishwajitsingh-rajput-27
          SETTING_JSON: '{"type":"dots","palette":"github-dark","background":"#070B14"}'

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: profile-3d-contrib
          keep_history: false
          commit_message: "chore(3d): update contribution 3d assets"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
